"""new

Revision ID: cbb40db1ed4c
Revises: 2025_01_27_0000
Create Date: 2025-08-23 12:48:45.699985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb40db1ed4c'
down_revision: Union[str, None] = '2025_01_27_0000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index('ix_prompts_endpoint')
        batch_op.drop_index('ix_prompts_prompt_type')
        batch_op.drop_column('endpoint')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoint', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_index('ix_prompts_prompt_type', ['prompt_type'], unique=False)
        batch_op.create_index('ix_prompts_endpoint', ['endpoint'], unique=False)

    # ### end Alembic commands ###
