"""idk

Revision ID: 15aaab98bda8
Revises: perf_indexes_001
Create Date: 2025-09-19 11:02:40.087204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15aaab98bda8'
down_revision: Union[str, None] = 'perf_indexes_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'phone_verifications',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('phone_number', sa.String(length=20), nullable=False),
        sa.Column('verification_code', sa.String(length=6), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.Column('attempts', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # indexes for phone_verifications
    op.create_index('ix_phone_verifications_id', 'phone_verifications', ['id'], unique=False)
    op.create_index('ix_phone_verifications_phone_number', 'phone_verifications', ['phone_number'], unique=False)

    # drop old perf indexes (if exist)
    op.drop_index('idx_meetings_created_at', table_name='meetings')
    op.drop_index('idx_meetings_user_created', table_name='meetings')

    op.drop_index('idx_segments_session_id', table_name='transcript_segments')
    op.drop_index('idx_segments_session_speaker', table_name='transcript_segments')

    # users table changes - online-safe sequence
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))

    # add as nullable first, backfill default, then set NOT NULL
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), nullable=True))
    op.execute("UPDATE users SET auth_provider = 'google' WHERE auth_provider IS NULL")
    op.alter_column('users', 'auth_provider', existing_type=sa.VARCHAR(length=20), nullable=False)

    # make email nullable
    op.alter_column('users', 'email', existing_type=sa.VARCHAR(length=255), nullable=True)

    # unique index on phone_number
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('auth_provider')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index('idx_segments_session_speaker', ['session_id', 'speaker_username'], unique=False)
        batch_op.create_index('idx_segments_session_id', ['session_id'], unique=False)

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index('idx_meetings_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_meetings_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('phone_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_verifications_phone_number'))
        batch_op.drop_index(batch_op.f('ix_phone_verifications_id'))

    op.drop_table('phone_verifications')
    # ### end Alembic commands ###
