import type { Meeting, MeetingSegment } from "./types"

export const createDemoMeeting = (): Meeting => {
  const now = new Date()
  const meetingStart = new Date(now.getTime() - 25 * 60 * 1000) // 25 minutes ago

  const segments: MeetingSegment[] = [
    {
      id: 1,
      session_id: "demo-session-001",
      google_meet_user_id: "user1",
      speaker_username: "Асель Сатпаева",
      timestamp: new Date(meetingStart.getTime()).toISOString(),
      text: "Добро пожаловать на еженедельную встречу команды! Сегодня мы обсудим прогресс по проекту и планы на следующую неделю.",
      version: 1,
      message_id: "msg1",
      created_at: new Date(meetingStart.getTime()).toISOString(),
    },
    {
      id: 2,
      session_id: "demo-session-001",
      google_meet_user_id: "user2",
      speaker_username: "Михаил Иванов",
      timestamp: new Date(meetingStart.getTime() + 30000).toISOString(),
      text: "Спасибо, Анна. Я готов поделиться обновлениями по разработке.",
      version: 1,
      message_id: "msg2",
      created_at: new Date(meetingStart.getTime() + 30000).toISOString(),
    },
    {
      id: 3,
      session_id: "demo-session-001",
      google_meet_user_id: "user1",
      speaker_username: "Асель Сатпаева",
      timestamp: new Date(meetingStart.getTime() + 45000).toISOString(),
      text: "Отлично! Давайте начнем с тебя, Михаил.",
      version: 1,
      message_id: "msg3",
      created_at: new Date(meetingStart.getTime() + 45000).toISOString(),
    },
    {
      id: 4,
      session_id: "demo-session-001",
      google_meet_user_id: "user2",
      speaker_username: "Михаил Иванов",
      timestamp: new Date(meetingStart.getTime() + 60000).toISOString(),
      text: "За прошлую неделю мы завершили интеграцию с API аутентификации. Все тесты проходят успешно, и функционал готов к развертыванию.",
      version: 1,
      message_id: "msg4",
      created_at: new Date(meetingStart.getTime() + 60000).toISOString(),
    },
    {
      id: 5,
      session_id: "demo-session-001",
      google_meet_user_id: "user2",
      speaker_username: "Михаил Иванов",
      timestamp: new Date(meetingStart.getTime() + 90000).toISOString(),
      text: "Также мы исправили критическую ошибку в системе уведомлений, которая влияла на производительность.",
      version: 1,
      message_id: "msg5",
      created_at: new Date(meetingStart.getTime() + 90000).toISOString(),
    },
    {
      id: 6,
      session_id: "demo-session-001",
      google_meet_user_id: "user3",
      speaker_username: "Дана Омарова",
      timestamp: new Date(meetingStart.getTime() + 120000).toISOString(),
      text: "Отличная работа, Михаил! Со стороны дизайна мы завершили макеты для новой панели администратора.",
      version: 1,
      message_id: "msg6",
      created_at: new Date(meetingStart.getTime() + 120000).toISOString(),
    },
    {
      id: 7,
      session_id: "demo-session-001",
      google_meet_user_id: "user3",
      speaker_username: "Дана Омарова",
      timestamp: new Date(meetingStart.getTime() + 150000).toISOString(),
      text: "Пользовательские интерфейсы стали более интуитивными, и мы добавили темную тему по многочисленным просьбам.",
      version: 1,
      message_id: "msg7",
      created_at: new Date(meetingStart.getTime() + 150000).toISOString(),
    },
    {
      id: 8,
      session_id: "demo-session-001",
      google_meet_user_id: "user4",
      speaker_username: "Абай Тлеухан",
      timestamp: new Date(meetingStart.getTime() + 180000).toISOString(),
      text: "Со стороны тестирования мы провели полную проверку новых функций. Обнаружили несколько мелких багов, но они уже исправлены.",
      version: 1,
      message_id: "msg8",
      created_at: new Date(meetingStart.getTime() + 180000).toISOString(),
    },
    {
      id: 9,
      session_id: "demo-session-001",
      google_meet_user_id: "user1",
      speaker_username: "Асель Сатпаева",
      timestamp: new Date(meetingStart.getTime() + 240000).toISOString(),
      text: "Замечательно! Теперь давайте обсудим планы на следующую неделю. Какие у нас приоритеты?",
      version: 1,
      message_id: "msg9",
      created_at: new Date(meetingStart.getTime() + 240000).toISOString(),
    },
    {
      id: 10,
      session_id: "demo-session-001",
      google_meet_user_id: "user2",
      speaker_username: "Михаил Иванов",
      timestamp: new Date(meetingStart.getTime() + 300000).toISOString(),
      text: "Я планирую начать работу над интеграцией с платежной системой. Это займет примерно 3-4 дня.",
      version: 1,
      message_id: "msg10",
      created_at: new Date(meetingStart.getTime() + 300000).toISOString(),
    },
    {
      id: 11,
      session_id: "demo-session-001",
      google_meet_user_id: "user3",
      speaker_username: "Дана Омарова",
      timestamp: new Date(meetingStart.getTime() + 360000).toISOString(),
      text: "А я буду работать над мобильной версией интерфейса. Нужно адаптировать все новые компоненты под мобильные устройства.",
      version: 1,
      message_id: "msg11",
      created_at: new Date(meetingStart.getTime() + 360000).toISOString(),
    },
    {
      id: 12,
      session_id: "demo-session-001",
      google_meet_user_id: "user4",
      speaker_username: "Абай Тлеухан",
      timestamp: new Date(meetingStart.getTime() + 420000).toISOString(),
      text: "Я продолжу автоматизацию тестирования. Хочу настроить CI/CD пайплайн для автоматического запуска тестов.",
      version: 1,
      message_id: "msg12",
      created_at: new Date(meetingStart.getTime() + 420000).toISOString(),
    },
    {
      id: 13,
      session_id: "demo-session-001",
      google_meet_user_id: "user1",
      speaker_username: "Асель Сатпаева",
      timestamp: new Date(meetingStart.getTime() + 480000).toISOString(),
      text: "Отлично! Есть ли какие-то блокеры или вопросы, которые нужно решить?",
      version: 1,
      message_id: "msg13",
      created_at: new Date(meetingStart.getTime() + 480000).toISOString(),
    },
    {
      id: 14,
      session_id: "demo-session-001",
      google_meet_user_id: "user2",
      speaker_username: "Михаил Иванов",
      timestamp: new Date(meetingStart.getTime() + 540000).toISOString(),
      text: "Мне нужна помощь с документацией API для платежной системы. Можем ли мы запросить более подробную информацию у поставщика?",
      version: 1,
      message_id: "msg14",
      created_at: new Date(meetingStart.getTime() + 540000).toISOString(),
    },
    {
      id: 15,
      session_id: "demo-session-001",
      google_meet_user_id: "user1",
      speaker_username: "Асель Сатпаева",
      timestamp: new Date(meetingStart.getTime() + 600000).toISOString(),
      text: "Конечно, я свяжусь с ними сегодня же. Что-то еще?",
      version: 1,
      message_id: "msg15",
      created_at: new Date(meetingStart.getTime() + 600000).toISOString(),
    },
    {
      id: 16,
      session_id: "demo-session-001",
      google_meet_user_id: "user3",
      speaker_username: "Дана Омарова",
      timestamp: new Date(meetingStart.getTime() + 660000).toISOString(),
      text: "У меня вопрос по цветовой схеме для мобильной версии. Можем ли мы использовать те же цвета, что и в десктопной версии?",
      version: 1,
      message_id: "msg16",
      created_at: new Date(meetingStart.getTime() + 660000).toISOString(),
    },
    {
      id: 17,
      session_id: "demo-session-001",
      google_meet_user_id: "user1",
      speaker_username: "Асель Сатпаева",
      timestamp: new Date(meetingStart.getTime() + 720000).toISOString(),
      text: "Да, давайте сохраним единообразие. Это поможет пользователям легче адаптироваться.",
      version: 1,
      message_id: "msg17",
      created_at: new Date(meetingStart.getTime() + 720000).toISOString(),
    },
    {
      id: 18,
      session_id: "demo-session-001",
      google_meet_user_id: "user4",
      speaker_username: "Абай Тлеухан",
      timestamp: new Date(meetingStart.getTime() + 780000).toISOString(),
      text: "Все понятно с моей стороны. Начну работу над пайплайном завтра утром.",
      version: 1,
      message_id: "msg18",
      created_at: new Date(meetingStart.getTime() + 780000).toISOString(),
    },
    {
      id: 19,
      session_id: "demo-session-001",
      google_meet_user_id: "user1",
      speaker_username: "Асель Сатпаева",
      timestamp: new Date(meetingStart.getTime() + 840000).toISOString(),
      text: "Отлично! Давайте также обсудим дедлайны. Когда мы планируем выпустить следующую версию?",
      version: 1,
      message_id: "msg19",
      created_at: new Date(meetingStart.getTime() + 840000).toISOString(),
    },
    {
      id: 20,
      session_id: "demo-session-001",
      google_meet_user_id: "user2",
      speaker_username: "Михаил Иванов",
      timestamp: new Date(meetingStart.getTime() + 900000).toISOString(),
      text: "Если все пойдет по плану, мы сможем выпустить версию к концу следующей недели.",
      version: 1,
      message_id: "msg20",
      created_at: new Date(meetingStart.getTime() + 900000).toISOString(),
    },
    {
      id: 21,
      session_id: "demo-session-001",
      google_meet_user_id: "user3",
      speaker_username: "Дана Омарова",
      timestamp: new Date(meetingStart.getTime() + 960000).toISOString(),
      text: "Согласна. Мобильная версия будет готова к четвергу, так что у нас будет время на финальное тестирование.",
      version: 1,
      message_id: "msg21",
      created_at: new Date(meetingStart.getTime() + 960000).toISOString(),
    },
    {
      id: 22,
      session_id: "demo-session-001",
      google_meet_user_id: "user4",
      speaker_username: "Абай Тлеухан",
      timestamp: new Date(meetingStart.getTime() + 1020000).toISOString(),
      text: "Тогда я проведу полное тестирование в пятницу и подготовлю отчет.",
      version: 1,
      message_id: "msg22",
      created_at: new Date(meetingStart.getTime() + 1020000).toISOString(),
    },
    {
      id: 23,
      session_id: "demo-session-001",
      google_meet_user_id: "user1",
      speaker_username: "Асель Сатпаева",
      timestamp: new Date(meetingStart.getTime() + 1080000).toISOString(),
      text: "Прекрасно! Кажется, у нас есть четкий план. Есть ли еще вопросы перед завершением встречи?",
      version: 1,
      message_id: "msg23",
      created_at: new Date(meetingStart.getTime() + 1080000).toISOString(),
    },
    {
      id: 24,
      session_id: "demo-session-001",
      google_meet_user_id: "user2",
      speaker_username: "Михаил Иванов",
      timestamp: new Date(meetingStart.getTime() + 1140000).toISOString(),
      text: "У меня все ясно. Спасибо за продуктивную встречу!",
      version: 1,
      message_id: "msg24",
      created_at: new Date(meetingStart.getTime() + 1140000).toISOString(),
    },
    {
      id: 25,
      session_id: "demo-session-001",
      google_meet_user_id: "user3",
      speaker_username: "Дана Омарова",
      timestamp: new Date(meetingStart.getTime() + 1200000).toISOString(),
      text: "Да, все понятно. До встречи на следующей неделе!",
      version: 1,
      message_id: "msg25",
      created_at: new Date(meetingStart.getTime() + 1200000).toISOString(),
    },
    {
      id: 26,
      session_id: "demo-session-001",
      google_meet_user_id: "user4",
      speaker_username: "Абай Тлеухан",
      timestamp: new Date(meetingStart.getTime() + 1260000).toISOString(),
      text: "Спасибо всем! Хорошей недели!",
      version: 1,
      message_id: "msg26",
      created_at: new Date(meetingStart.getTime() + 1260000).toISOString(),
    },
    {
      id: 27,
      session_id: "demo-session-001",
      google_meet_user_id: "user1",
      speaker_username: "Асель Сатпаева",
      timestamp: new Date(meetingStart.getTime() + 1320000).toISOString(),
      text: "Отлично! Встреча завершена. Увидимся на следующей неделе в то же время. Всем продуктивной работы!",
      version: 1,
      message_id: "msg27",
      created_at: new Date(meetingStart.getTime() + 1320000).toISOString(),
    },
  ]

  return {
    unique_session_id: "demo-session-001",
    meeting_id: "demo-meeting-001",
    user_id: "current-user",
    title: "Еженедельная встреча команды - Демо",
    segments,
    created_at: meetingStart.toISOString(),
    speakers: ["Асель Сатпаева", "Михаил Иванов", "Дана Омарова", "Абай Тлеухан"],
  }
}

export const DEMO_MEETING = createDemoMeeting()
