#!/bin/bash
#==============================================================================
# Script: rotate_backend_logs.sh
# Purpose: Rotate and compress backend application logs
# Schedule: Weekly on Sundays at 5:00 AM
# VM: VM2 (Backend)
# Cron: 0 5 * * 0 /opt/dapmeet/scripts/cron/rotate_backend_logs.sh
#==============================================================================

set -euo pipefail

# Configuration
LOG_DIR="/var/log/dapmeet"
MAX_SIZE="100M"
ROTATE_COUNT=5
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
STATUS_LOG="$LOG_DIR/rotation_status.log"

# Logging function
log() {
    echo "[$TIMESTAMP] $1" | tee -a "$STATUS_LOG"
}

log "Starting backend logs rotation..."

# Ensure log directory exists
if [ ! -d "$LOG_DIR" ]; then
    log "Log directory $LOG_DIR does not exist, creating..."
    mkdir -p "$LOG_DIR"
fi

# Create logrotate configuration
LOGROTATE_CONF="/tmp/dapmeet-logrotate-$$.conf"

cat > "$LOGROTATE_CONF" << EOF
# Dapmeet Backend Log Rotation Configuration
# Generated by rotate_backend_logs.sh

$LOG_DIR/*.log {
    size $MAX_SIZE
    rotate $ROTATE_COUNT
    compress
    delaycompress
    missingok
    notifempty
    create 640 root dapmeet
    sharedscripts
    postrotate
        # Reload applications to use new log files
        /usr/bin/docker kill --signal=USR1 dapmeet-backend 2>/dev/null || true
    endscript
}

$LOG_DIR/backend.log {
    size $MAX_SIZE
    rotate $ROTATE_COUNT
    compress
    delaycompress
    missingok
    notifempty
    create 640 dapmeet-backend dapmeet
}

$LOG_DIR/worker.log {
    size $MAX_SIZE
    rotate $ROTATE_COUNT
    compress
    delaycompress
    missingok
    notifempty
    create 640 dapmeet-worker dapmeet
}
EOF

log "Generated logrotate configuration at $LOGROTATE_CONF"

# Get log sizes before rotation
log "Current log sizes:"
for logfile in "$LOG_DIR"/*.log; do
    if [ -f "$logfile" ]; then
        size=$(ls -lh "$logfile" | awk '{print $5}')
        log "  $(basename "$logfile"): $size"
    fi
done

# Execute logrotate
log "Executing logrotate..."
if /usr/sbin/logrotate -v -f "$LOGROTATE_CONF" >> "$STATUS_LOG" 2>&1; then
    log "Logrotate completed successfully"
else
    log "WARNING: Logrotate reported issues (check status log)"
fi

# Cleanup
rm -f "$LOGROTATE_CONF"

# Additional manual compression for any uncompressed rotated logs
log "Compressing any uncompressed rotated logs..."
find "$LOG_DIR" -name "*.log.[0-9]*" ! -name "*.gz" -exec gzip {} \; 2>/dev/null || true

# Count rotated files
ROTATED_COUNT=$(find "$LOG_DIR" -name "*.log.*.gz" | wc -l)
TOTAL_SIZE=$(du -sh "$LOG_DIR" 2>/dev/null | cut -f1)

log "=== Rotation Summary ==="
log "Rotated log files: $ROTATED_COUNT"
log "Total log directory size: $TOTAL_SIZE"
log "Backend logs rotation completed"

exit 0


